export const IMBALANCE_NOTE = "Start with the LEFT side every time. Match the same reps with the right — never do more. If you notice a gap of 2 or more reps, hold the same weight on both sides until they match. Once they match for two sessions in a row, add weight to both together.";

export const schedule = [
  {
    day: "MON", label: "Push", type: "push",
    focus: "Push — Chest Focus",
    muscles: ["Chest", "Shoulders", "Triceps"],
    cardio: { name: "Incline Treadmill", protocol: "4.0–4.5 mph at 8–12% incline for 20 minutes", zone: "Zone 3 (65–75% max HR)", feel: "Breathing is noticeably elevated. Short sentences only — not fully conversational. That's the target and it stays there the whole 20 minutes." },
    exercises: [
      { name: "Dumbbell Bench Press", muscles: ["Chest", "Front Delt", "Tricep"], category: "Compound Bilateral", order: 1, sets: 4, reps: "6–10", rest: "2–3 min", eccentric: "3s down", why: "Opens the session as the primary chest compound. Dumbbells mean each side has to generate its own force independently — the right side cannot carry the left, which is what makes them better than a barbell for catching and correcting asymmetry.", form: [{ label: "Setup", text: "Lie flat with feet firmly planted. Pull the shoulder blades together and down toward your back pockets — hold that position the entire set." }, { label: "Elbows", text: "Hold the dumbbells at chest height with elbows at roughly 45–60° from your torso. Wrists stacked directly over elbows." }, { label: "Descent", text: "Take 3 full seconds to lower until you feel a deep stretch across the chest. Don't let elbows drop below your torso plane." }, { label: "Press", text: "Drive back up along the same arc. Think about pushing the chest up toward the ceiling. Stop just short of full lockout so the chest stays under tension." }, { label: "Breathing", text: "Breathe in on the way down. Brace your core hard at the bottom, then exhale as you press." }, { label: "Watch for", text: "Hips lifting off the bench, wrists collapsing backward, or dumbbells drifting too far over the face or stomach." }] },
      { name: "Incline Dumbbell Press", muscles: ["Upper Chest", "Front Delt", "Tricep"], category: "Compound Bilateral", order: 2, sets: 3, reps: "8–12", rest: "2 min", eccentric: "3s down", why: "The incline shifts the load to the clavicular head of the pec — what builds the upper chest shelf. Second compound while the CNS is still fresh.", form: [{ label: "Setup", text: "Set the bench to 30–45°. Any steeper and it becomes a shoulder press. Same scapular retraction as the flat press." }, { label: "Descent", text: "Lower until the dumbbells are at upper chest level and you feel the upper pec stretch. If there's no stretch, go slightly deeper." }, { label: "Press", text: "Drive up and very slightly inward. Exhale on the press. Stop just before full lockout." }, { label: "Watch for", text: "Bench set too steep, neck craning forward, or cutting the range of motion short at the bottom." }] },
      { name: "Single-Arm Overhead DB Press", muscles: ["Shoulder", "Tricep", "Core"], category: "Compound Unilateral", order: 3, sets: 3, reps: "10–12 each side", rest: "90 sec", eccentric: "3s down", imbalanceNote: IMBALANCE_NOTE, why: "Shoulder strength is one of the most common places left and right diverge. Each side has to stabilize and press alone here.", form: [{ label: "Setup", text: "Seated on an upright bench with one dumbbell at shoulder height, palm facing forward." }, { label: "Core", text: "Big breath in and brace hard before every single rep. Your torso must not lean away from the working side." }, { label: "Press", text: "Drive straight up with the dumbbell tracking in line with your ear. Exhale on the press." }, { label: "Watch for", text: "Lateral torso lean, wrist collapsing backward, or the elbow swinging forward during the press." }] },
      { name: "Cable Fly (Low-to-High)", muscles: ["Lower Chest", "Front Delt"], category: "Isolation Bilateral", order: 4, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "2s return", why: "Cable keeps tension on the chest throughout the full arc. A dumbbell fly drops to near zero resistance at peak contraction.", form: [{ label: "Setup", text: "Both cables at the lowest position. Slight forward lean from the hips." }, { label: "Arms", text: "Lock in a slight elbow bend and keep it fixed the entire rep." }, { label: "Arc", text: "Sweep both handles up and across in a wide arc." }, { label: "Top", text: "Squeeze the chest hard at the top for one full second." }, { label: "Watch for", text: "Elbow bend changing mid-rep, shrugging the shoulders, or rotating the torso." }] },
      { name: "Lateral Raise", muscles: ["Side Delt"], category: "Isolation Bilateral", order: 5, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "2s down", why: "Side delts get almost no stimulus from pressing movements and need direct work. This is what builds shoulder width.", form: [{ label: "Setup", text: "Stand with a slight forward lean from the hips. Dumbbells hang in front of the hips." }, { label: "Raise", text: "Lead with the elbows. Think pouring water from a jug — pinky slightly higher than thumb. Stop at shoulder height." }, { label: "Watch for", text: "Shrugging the traps, raising above shoulder height, or letting the arms drop quickly." }] },
      { name: "Overhead Tricep Extension", muscles: ["Tricep Long Head"], category: "Isolation Bilateral", order: 6, sets: 3, reps: "10–15", rest: "90 sec", eccentric: "3s down", why: "The only tricep exercise that fully stretches the long head — the largest portion. Every other variation misses this.", form: [{ label: "Setup", text: "Cable: high pulley, face away, hold rope overhead. DB: hold one dumbbell with both hands overhead." }, { label: "Upper arms fixed", text: "Upper arms stay completely still. Only the forearms move." }, { label: "Descent", text: "3 full seconds down until there's a deep stretch in the tricep." }, { label: "Watch for", text: "Elbows flaring wide, upper arms moving, or not reaching the full stretch at the bottom." }] },
      { name: "Tricep Rope Pushdown", muscles: ["Tricep"], category: "Isolation Bilateral", order: 7, sets: 2, reps: "15–20", rest: "60 sec", eccentric: "2s return", why: "High-rep finisher for the lateral and medial tricep heads — different stimulus from the overhead extension.", form: [{ label: "Setup", text: "Cable at the top with a rope attachment. Grip the ends with thumbs pointing up." }, { label: "Upper arms", text: "Pin the elbows to the ribcage — they do not move." }, { label: "Push", text: "Drive down to full extension and spread the rope ends apart at the bottom." }, { label: "Watch for", text: "Upper arms lifting away from the body or letting the rope snap back." }] },
    ],
  },
  {
    day: "TUE", label: "Pull", type: "pull",
    focus: "Pull — Back Focus",
    muscles: ["Back", "Biceps", "Rear Delts"],
    cardio: { name: "Rowing Machine or Incline Treadmill", protocol: "Rower: moderate pace, damper 4–5 for 20 minutes. Treadmill: 4.0 mph at 10% incline.", zone: "Zone 3 (65–75% max HR)", feel: "The rower reinforces the pulling pattern at low load post-session. Breathing elevated throughout." },
    exercises: [
      { name: "Lat Pulldown (Wide Overhand)", muscles: ["Lats", "Bicep", "Rear Delt"], category: "Compound Bilateral", order: 1, sets: 4, reps: "6–10", rest: "2–3 min", eccentric: "3s return", why: "Heaviest pull of the session, so it goes first. Wide grip builds lat width and develops the strength pattern for unassisted pull-ups.", form: [{ label: "Setup", text: "Grip just outside shoulder width. Lock knees firmly under the pad. Lean back about 20°." }, { label: "Pull", text: "Think about driving the elbows down toward your back pockets. Bring the bar to the upper chest." }, { label: "Return", text: "3 full seconds back to the top. Let the bar travel all the way up — the shoulder blades spread at the top. That full stretch is part of the range." }, { label: "Watch for", text: "Pulling the bar behind the neck, excessive lower back arch, or cutting the return short." }] },
      { name: "Seated Cable Row (Neutral Grip)", muscles: ["Mid Back", "Lats", "Bicep"], category: "Compound Bilateral", order: 2, sets: 3, reps: "10–12", rest: "2 min", eccentric: "3s return", why: "Mid-back thickness. Neutral grip lets you load heavier and hits the rhomboids and mid-traps alongside the lats.", form: [{ label: "Setup", text: "Sit tall with feet flat on the footplates. Lean slightly forward from the hips at the start." }, { label: "Row", text: "Drive the elbows straight back and pull the handle to the lower sternum. Squeeze the shoulder blades together and hold for one second." }, { label: "Return", text: "3 full seconds to full arm extension. Let shoulder blades protract forward at the end." }, { label: "Watch for", text: "Leaning back with the lower back to help, shoulder rounding on the return, or jerking the weight." }] },
      { name: "Single-Arm Dumbbell Row", muscles: ["Lats", "Mid Back", "Bicep"], category: "Compound Unilateral", order: 3, sets: 3, reps: "10–12 each side", rest: "90 sec", eccentric: "3s down", imbalanceNote: IMBALANCE_NOTE, why: "Any left/right back strength asymmetry cannot be addressed with bilateral exercises alone — each side has to work independently.", form: [{ label: "Setup", text: "One knee and same-side hand on a bench. Working arm hanging straight down. Back flat." }, { label: "Stretch first", text: "Before pulling, let the arm fully extend and the shoulder blade drift forward slightly." }, { label: "Drive", text: "Pull the elbow straight back and slightly up — toward your back pocket. Pull until dumbbell reaches the lower chest." }, { label: "Watch for", text: "Rotating the torso to swing the weight, or shortcutting the stretch at the bottom." }] },
      { name: "Straight-Arm Cable Pulldown", muscles: ["Lats"], category: "Isolation Bilateral", order: 4, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "2s return", why: "Isolates the lats without involving the biceps at all. Builds the lat mind-muscle connection that makes every pull more effective.", form: [{ label: "Setup", text: "Cable at the top. Stand about 2 feet back with a slight hip hinge, arms extended overhead." }, { label: "Arms stay straight", text: "Lock in a slight elbow bend and do not change it. Any significant bend and the lat isolation is gone." }, { label: "Arc", text: "Sweep the bar down in a wide arc to the hips." }, { label: "Watch for", text: "Significant elbow bending or the cable yanking the torso forward." }] },
      { name: "Alternating Dumbbell Curl", muscles: ["Bicep"], category: "Isolation Bilateral", order: 5, sets: 3, reps: "10–12 each arm", rest: "90 sec", eccentric: "3s down", why: "Alternating allows full supination at the top of each rep, maximizing peak contraction.", form: [{ label: "Supination", text: "As you curl, rotate the palm upward. By the top, pinky should be higher than thumb." }, { label: "Upper arm", text: "Pin the upper arm to your side the entire rep." }, { label: "Return", text: "3 full seconds back to a complete dead hang. The bottom stretch is a growth stimulus." }, { label: "Watch for", text: "Swinging the torso, elbows drifting forward, or stopping short at the bottom." }] },
      { name: "Incline Dumbbell Curl", muscles: ["Bicep Long Head"], category: "Isolation Bilateral", order: 6, sets: 3, reps: "10–12", rest: "90 sec", eccentric: "3s down", why: "The incline position places the long head of the bicep on full stretch before the curl begins. Best exercise for bicep peak.", form: [{ label: "Setup", text: "Bench at 45–60°. Arms hang freely behind the torso — behind the body when extended." }, { label: "Key point", text: "Don't let elbows drift forward before curling — that removes the long head stretch immediately." }, { label: "Return", text: "3 slow seconds back to full extension." }, { label: "Watch for", text: "Elbows drifting forward, momentum at the bottom, or cutting range of motion short." }] },
      { name: "Rear Delt Fly (Bent-Over)", muscles: ["Rear Delt", "Upper Back"], category: "Isolation Bilateral", order: 7, sets: 3, reps: "15–20", rest: "60 sec", eccentric: "2s return", why: "Critical for shoulder health under a program with four push sessions per week. High reps are intentional — rear delts are slow-twitch dominant.", form: [{ label: "Setup", text: "Hinge forward until the torso is nearly parallel to the floor. Use lighter dumbbells." }, { label: "Raise", text: "Lead with the elbows. Spread the wings. Squeeze the back of the shoulders at the top." }, { label: "Watch for", text: "Going too heavy causing body swing, or shrugging instead of contracting the rear delt." }] },
    ],
  },
  {
    day: "WED", label: "Legs", type: "legs",
    focus: "Legs — Posterior Chain",
    muscles: ["Glutes", "Hamstrings", "Quads", "Calves"],
    cardio: { name: "Stationary Bike", protocol: "Resistance 6–8 out of 10 for 20 minutes", zone: "Zone 3 (65–75% max HR)", feel: "Legs will be fatigued — that's fine. Hold the elevated heart rate steady. Consistent pedaling, not sprinting." },
    exercises: [
      { name: "Hip Thrust (Barbell or Machine)", muscles: ["Glutes", "Hamstrings"], category: "Compound Bilateral", order: 1, sets: 4, reps: "8–10", rest: "2–3 min", eccentric: "3s down", why: "The single most effective glute exercise — loads the glute at full hip extension where peak resistance occurs. Progressive overload is the primary week-over-week focus here.", form: [{ label: "Setup", text: "Upper back on bench just below the shoulder blades. Feet flat, hip-width, toes slightly out. Barbell padded across the hip crease." }, { label: "Before driving", text: "Breathe in, brace the core, tuck the chin. Chin stays tucked the entire set." }, { label: "Drive", text: "Push through the heels. Drive hips up until the body forms a straight line from shoulders to knees." }, { label: "Top", text: "Squeeze glutes hard and hold for one full second. If you feel it in the lower back the hips are going too high." }, { label: "Watch for", text: "Lower back hyperextending, knees caving inward, or pushing through the toes instead of heels." }] },
      { name: "Romanian Deadlift (Dumbbell)", muscles: ["Hamstrings", "Glutes", "Lower Back"], category: "Compound Bilateral", order: 2, sets: 4, reps: "8–10", rest: "2–3 min", eccentric: "3–4s down", why: "Primary hamstring compound second in session while the posterior chain is maximally warm. Loads the hamstrings in a stretched position — stretch-loaded training produces superior hypertrophy.", form: [{ label: "Setup", text: "Stand holding dumbbells in front of the thighs. Feet hip-width, soft fixed knee bend — don't change it." }, { label: "Hinge", text: "Push the hips backward — not downward. This is a hip hinge, not a squat. Dumbbells stay close to the legs." }, { label: "Depth", text: "Lower until a deep hamstring pull — usually mid-shin to ankle. The back must stay flat." }, { label: "Watch for", text: "Squatting the weight by bending the knees, lower back rounding, or dumbbells drifting away from the body." }] },
      { name: "Leg Press", muscles: ["Quads", "Glutes"], category: "Compound Bilateral", order: 3, sets: 3, reps: "10–12", rest: "2 min", eccentric: "3s down", why: "Third compound after the posterior chain has been loaded. Targets the quads heavily with the machine removing balance demands.", form: [{ label: "Foot position", text: "Hip-width at mid-platform, toes slightly out." }, { label: "Core", text: "Lower back pressed into the seat pad throughout. If it peels off, too deep or too heavy." }, { label: "Press", text: "Drive through the whole foot. Stop just short of full knee lockout." }, { label: "Watch for", text: "Lower back lifting off the pad, knees caving, full lockout at the top." }] },
      { name: "Bulgarian Split Squat (Dumbbell)", muscles: ["Quads", "Glutes", "Hamstrings"], category: "Compound Unilateral", order: 4, sets: 3, reps: "8–10 each leg", rest: "2 min", eccentric: "3s down", imbalanceNote: IMBALANCE_NOTE, why: "Addresses the half-inch left/right thigh size difference directly. The right leg cannot compensate for the left when each is working alone.", form: [{ label: "Setup", text: "2 feet in front of a bench. Top of rear foot on the bench — laces down. Front foot far enough forward that the shin stays vertical when you lower." }, { label: "Descent", text: "Drop straight down rather than forward. Front knee stays over the toes. Lower until rear knee is 2 inches from the floor." }, { label: "Torso", text: "Keep the chest up throughout." }, { label: "Watch for", text: "Rear foot wrong (top of foot, not ankle), front knee caving, torso collapsing forward." }] },
      { name: "Leg Extension", muscles: ["Quads"], category: "Isolation Bilateral", order: 5, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "3s down", why: "Direct quad isolation filling in the terminal range compound movements miss.", form: [{ label: "Setup", text: "Pad just above the ankle. Back flat on the seat." }, { label: "Extension", text: "Extend to full knee extension and pause one second at the top." }, { label: "Return", text: "3 full seconds back. Do not let the stack clatter." }] },
      { name: "Standing Calf Raise", muscles: ["Gastrocnemius"], category: "Isolation Bilateral", order: 6, sets: 4, reps: "15–20", rest: "60 sec", eccentric: "3s down", why: "Gastrocnemius targeted with straight knee. Full range is required — partial reps produce almost nothing.", form: [{ label: "Stretch", text: "Start by dropping heels as far below the step as possible. This is what most people skip." }, { label: "Rise", text: "Drive onto the ball of the foot as high as possible. Hold one second at the top." }, { label: "Watch for", text: "Bouncing at the bottom, not reaching full elevation, bending the knees." }] },
    ],
  },
  {
    day: "THU", label: "Push", type: "push",
    focus: "Push — Shoulder Focus",
    muscles: ["Shoulders", "Chest", "Triceps"],
    cardio: { name: "Incline Treadmill", protocol: "4.0–4.5 mph at 8–12% incline for 20 minutes", zone: "Zone 3 (65–75% max HR)", feel: "Same target as Monday. Short sentences only, breathing noticeably elevated." },
    exercises: [
      { name: "Seated Dumbbell Overhead Press", muscles: ["Shoulder", "Tricep", "Upper Chest"], category: "Compound Bilateral", order: 1, sets: 4, reps: "6–10", rest: "2–3 min", eccentric: "3s down", why: "Primary shoulder compound first. Seated removes lower back involvement. Dumbbells let each shoulder work independently.", form: [{ label: "Setup", text: "Upright bench at 90°. Dumbbells at shoulder height, palms forward." }, { label: "Core", text: "Breathe in, brace hard, press lower back into the bench. It stays in contact throughout." }, { label: "Press", text: "Drive both dumbbells up in a slight inward arc. Exhale on the press." }, { label: "Watch for", text: "Lower back arching away from the bench, wrists collapsing backward." }] },
      { name: "Arnold Press", muscles: ["All 3 Delt Heads", "Tricep"], category: "Compound Bilateral", order: 2, sets: 3, reps: "10–12", rest: "2 min", eccentric: "3s down", why: "Works all three deltoid heads through the rotation arc — more complete shoulder stimulus than a standard press.", form: [{ label: "Start", text: "Hold dumbbells in front of the face with palms facing you. Elbows at 90° pointing forward." }, { label: "Movement", text: "As you press up, rotate wrists so palms face away by the time arms are extended. Rotation and press are one movement." }, { label: "Return", text: "Reverse exactly — lower while rotating palms back toward you. 3 full seconds." }, { label: "Watch for", text: "Rushing through the rotation, starting with arms too wide." }] },
      { name: "Incline Dumbbell Press", category: "Compound Bilateral", order: 3, sets: 3, reps: "8–12", rest: "2 min", eccentric: "3s down", why: "Second weekly upper chest session. Placed third after shoulder compounds since chest is secondary today.", form: [{ label: "Form", text: "Same as Monday. Bench at 30–45°, scapular retraction held, 3-second descent." }, { label: "Load", text: "Expect to use slightly less than Monday since shoulder work came first — log both." }] },
      { name: "Single-Arm Overhead DB Press", category: "Compound Unilateral", order: 4, sets: 3, reps: "10–12 each side", rest: "90 sec", eccentric: "3s down", imbalanceNote: IMBALANCE_NOTE, why: "Second weekly unilateral shoulder check. Log each side separately and compare to Monday — if the gap is narrowing, the correction is working.", form: [{ label: "Form", text: "Identical to Monday. Core braced hard before every rep, no lateral torso lean." }, { label: "Track", text: "Log left and right weights separately. The goal over 8–12 weeks is both sides matching." }] },
      { name: "Cable Lateral Raise (Single-Arm)", muscles: ["Side Delt"], category: "Isolation Unilateral", order: 5, sets: 3, reps: "15–20 each side", rest: "90 sec", eccentric: "2s return", imbalanceNote: "If one shoulder is noticeably weaker, start there and match reps. Cable reveals asymmetry more clearly because tension is constant.", why: "Cable keeps tension at the bottom of the range where dumbbells have near zero resistance.", form: [{ label: "Setup", text: "Stand side-on to the stack. Cable at lowest position. Grab with the hand farthest from the stack." }, { label: "Raise", text: "Lift the arm out to the side leading with the elbow. Stop at shoulder height." }, { label: "Watch for", text: "Shrugging to assist, raising above shoulder height, or rotating the torso." }] },
      { name: "Cable Fly (Low-to-High)", category: "Isolation Bilateral", order: 6, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "2s return", why: "Second weekly chest isolation. Bilateral to keep it efficient.", form: [{ label: "Form", text: "Same as Monday. Cable lowest, sweep up and across, squeeze hard at the top." }] },
      { name: "Tricep Rope Pushdown", category: "Isolation Bilateral", order: 7, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "2s return", why: "Second weekly tricep isolation — lateral and medial head focus. Different stimulus from Monday's overhead extension.", form: [{ label: "Form", text: "Same as Monday. Elbows pinned, spread the rope at full extension." }] },
    ],
  },
  {
    day: "FRI", label: "Pull", type: "pull",
    focus: "Pull — Bicep Focus & Core",
    muscles: ["Back", "Biceps", "Rear Delts", "Core"],
    cardio: { name: "Rowing Machine", protocol: "Moderate pace at damper 4–5 for 20 minutes", zone: "Zone 3 (65–75% max HR)", feel: "Rower post-Pull keeps the back and arms engaged through the recovery window. Breathing elevated." },
    exercises: [
      { name: "Pull-Up (or Assisted Pull-Up)", muscles: ["Lats", "Bicep", "Core"], category: "Compound Bilateral", order: 1, sets: 4, reps: "Max reps (or 6–8 assisted)", rest: "2–3 min", eccentric: "3s down", why: "Primary compound and the key weekly progress marker. Currently at 6 wide-grip — tracking rep increases week over week is one of the clearest indicators of lat and bicep development.", form: [{ label: "Grip", text: "Overhand, just outside shoulder width. Full dead hang at the bottom." }, { label: "Before pulling", text: "Depress and retract the shoulder blades before initiating the pull." }, { label: "Pull", text: "Drive the elbows down and back. Pull until the chin clears the bar." }, { label: "Eccentric", text: "3 full seconds on the way down. This is the fastest path to unassisted pull-ups." }, { label: "Watch for", text: "Kipping, not reaching a dead hang at the bottom, or craning the neck." }] },
      { name: "Chest-Supported DB Row", muscles: ["Mid Back", "Lats", "Rear Delt"], category: "Compound Bilateral", order: 2, sets: 3, reps: "10–12", rest: "2 min", eccentric: "3s down", why: "Chest support removes lower back involvement completely — pure mid-back work. Allows heavier loading without lower back fatigue late in the week.", form: [{ label: "Setup", text: "Incline bench at 30–45°. Lie face-down, chest on the pad. Arms hanging straight down." }, { label: "Row", text: "Drive both elbows straight back and up. Squeeze lat and mid-back hard at the peak." }, { label: "Return", text: "3 seconds down to a full dead hang." }, { label: "Watch for", text: "Lifting the head to assist, rotating the torso, or cutting range short." }] },
      { name: "Face Pull (Rope Attachment)", muscles: ["Rear Delt", "External Rotators"], category: "Isolation Bilateral", order: 3, sets: 4, reps: "15–20", rest: "90 sec", eccentric: "2s return", why: "Rear delts are the priority here — also trains external rotation essential for shoulder health under four push sessions per week.", form: [{ label: "Setup", text: "Cable at face height. Grip rope ends with thumbs pointing up." }, { label: "Pull", text: "Pull toward the face, splitting the ends apart. Elbows rise high and wide." }, { label: "Top", text: "Wrists beside ears, elbows high. Squeeze rear delts. Hold one second." }, { label: "Watch for", text: "Elbows dropping low turning it into a row, or pulling to the neck instead of the face." }] },
      { name: "Hammer Curl", muscles: ["Brachialis", "Bicep"], category: "Isolation Bilateral", order: 4, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "3s down", why: "Neutral grip targets the brachialis — the muscle underneath the bicep that pushes the bicep up when developed.", form: [{ label: "Grip", text: "Neutral grip throughout — thumb pointing up at all times. No rotation." }, { label: "Form", text: "Upper arm pinned to the side. Full extension at the bottom. Full contraction at the top." }, { label: "Watch for", text: "Wrist supinating mid-rep, upper arm swinging forward." }] },
      { name: "Cable Curl (Low Pulley)", muscles: ["Bicep"], category: "Isolation Bilateral", order: 5, sets: 3, reps: "12–15", rest: "90 sec", eccentric: "3s down", why: "Cable provides resistance at full arm extension — the point where dumbbell resistance drops to almost nothing.", form: [{ label: "Key difference", text: "Pause briefly at full extension and feel the cable pulling. That bottom tension is what makes this different from dumbbell curls." }, { label: "Return", text: "3 full seconds back to extension." }] },
      { name: "Dead Bug", muscles: ["Deep Core", "TVA"], category: "Core Stage 1", order: 6, sets: 3, reps: "8–10 each side", rest: "60 sec", eccentric: "3s lowering", why: "Stage 1 core — trains the deep TVA to stabilize the spine against extension. The foundation every compound lift depends on.", form: [{ label: "Position", text: "Lie on back. Arms up, knees at 90° in the air. Lower back pressed fully into the floor — no gap." }, { label: "Brace", text: "Exhale fully, then brace hard. Back stays flat. The moment it lifts, the set is over for that rep." }, { label: "Movement", text: "Slowly lower the right arm overhead and left leg toward the floor simultaneously." }, { label: "Watch for", text: "Any gap between the lower back and floor, holding breath, or moving too quickly." }] },
      { name: "Pallof Press (Cable)", muscles: ["Core", "Obliques"], category: "Core Stage 2", order: 7, sets: 3, reps: "10–12 each side", rest: "60 sec", eccentric: "2s return", why: "Stage 2 — trains the core to resist rotational forces, which is what it actually does during squats, deadlifts, presses, and rows.", form: [{ label: "Setup", text: "Stand side-on to the cable stack, cable at chest height." }, { label: "Press", text: "Press the handle straight out until arms are fully extended. Hold 1–2 seconds." }, { label: "The work", text: "The isometric hold is where the core is working. Keep shoulders and hips square." }, { label: "Watch for", text: "Torso rotating toward the cable or feet shifting." }] },
      { name: "Hanging Knee Raise", muscles: ["Abs", "Hip Flexors"], category: "Core Stage 3", order: 8, sets: 3, reps: "10–15", rest: "60 sec", eccentric: "3s down", why: "Stage 3 — loaded flexion progressed from Dead Bug. Posterior pelvic tilt at the top recruits the abs rather than just hip flexors.", form: [{ label: "Hang", text: "Dead hang from a pull-up bar with shoulder blades depressed and retracted." }, { label: "Raise", text: "Bring knees up toward the chest. At the top, tilt the pelvis posteriorly — curl the tailbone toward the ceiling." }, { label: "Return", text: "3 full seconds back to a complete dead hang." }, { label: "Watch for", text: "Swinging for momentum, not tilting the pelvis at the top, or legs dropping fast." }] },
    ],
  },
  {
    day: "SAT", label: "Legs", type: "legs",
    focus: "Legs — Quad Focus & Core",
    muscles: ["Quads", "Glutes", "Hamstrings", "Calves", "Core"],
    cardio: { name: "Stationary Bike or Brisk Walk", protocol: "Bike: resistance 6–8 out of 10 for 20 minutes. Walk: brisk with hills if available.", zone: "Zone 3 (65–75% max HR)", feel: "End of the training week. Legs will be more fatigued than Wednesday — hold the heart rate target regardless." },
    exercises: [
      { name: "Leg Press", category: "Compound Bilateral", order: 1, sets: 4, reps: "8–10", rest: "2–3 min", eccentric: "3s down", why: "Quad-focused bilateral compound placed first today. Lower rep range and higher load than Wednesday for a different stimulus.", form: [{ label: "Today", text: "Slightly lower foot position than Wednesday to increase quad bias. Same core brace throughout." }] },
      { name: "Hip Thrust (Barbell or Machine)", category: "Compound Bilateral", order: 2, sets: 3, reps: "10–12", rest: "2 min", eccentric: "3s down", why: "Second weekly glute compound. Glutes handle high frequency well and need the volume. Progressive overload still applies.", form: [{ label: "Form", text: "Same as Wednesday. Chin tucked, core braced, drive through heels. Full extension with one-second hard squeeze." }, { label: "Load", text: "Leg press came first so the glutes are pre-fatigued. Slightly less than Wednesday is normal — still add reps or weight vs last Saturday." }] },
      { name: "Bulgarian Split Squat (Dumbbell)", category: "Compound Unilateral", order: 3, sets: 3, reps: "10–12 each leg", rest: "90 sec", eccentric: "3s down", imbalanceNote: IMBALANCE_NOTE, why: "Second weekly unilateral leg session. Higher rep range than Wednesday for additional volume. Left leg first every time.", form: [{ label: "Form", text: "Identical to Wednesday. Left leg first. Chest up. Drive through the front heel." }, { label: "Rep range", text: "Wednesday was 8–10 for strength. Today is 10–12 for volume. Use slightly less weight." }] },
      { name: "Single-Leg Hamstring Curl", muscles: ["Hamstrings"], category: "Isolation Unilateral", order: 4, sets: 3, reps: "12–15 each leg", rest: "90 sec", eccentric: "3s return", imbalanceNote: IMBALANCE_NOTE, why: "Most direct tool for finding and closing the left/right hamstring strength difference contributing to the thigh size asymmetry.", form: [{ label: "Extension", text: "Full leg extension before every rep. The stretch at the bottom is where the stimulus is." }, { label: "Curl", text: "Curl heel toward glute for full contraction at the top." }, { label: "Return", text: "3 full seconds back to full extension. This eccentric is the most important part." }, { label: "Watch for", text: "Hips lifting off the pad, short range of motion, or weight dropping fast." }] },
      { name: "Goblet Squat", muscles: ["Quads", "Glutes", "Core"], category: "Compound Bilateral", order: 5, sets: 3, reps: "15–20", rest: "90 sec", eccentric: "3s down", why: "High-rep quad and glute metabolic finisher. Goblet position enforces upright torso maximizing quad depth.", form: [{ label: "Hold", text: "One dumbbell vertically at chest. Elbows point downward." }, { label: "Descent", text: "Sit down and between the knees. Elbows track inside the knees at the bottom." }, { label: "Watch for", text: "Heels lifting, torso collapsing forward, knees caving on the way up." }] },
      { name: "Seated Calf Raise", muscles: ["Soleus"], category: "Isolation Bilateral", order: 6, sets: 4, reps: "15–20", rest: "60 sec", eccentric: "3s down", why: "Seated targets the soleus — a different, deeper calf muscle the standing raise barely touches.", form: [{ label: "Range", text: "Full heel drop at the bottom, rise as high as possible. Hold one second at the top." }, { label: "Return", text: "3 controlled seconds. No bouncing." }] },
      { name: "Ab Wheel Rollout", muscles: ["Core", "Lats"], category: "Core Stage 3", order: 7, sets: 3, reps: "8–10", rest: "60 sec", eccentric: "3s out", why: "Stage 3 core anti-extension — requires the deep core to resist spinal extension over a large arc. Direct progression from Dead Bug.", form: [{ label: "Brace", text: "Before moving, breathe in and brace hard. Lower back must stay neutral the entire roll." }, { label: "Roll", text: "3 seconds out as far as possible while maintaining neutral spine." }, { label: "Return", text: "Pull back using abs and lats together. Brace throughout." }, { label: "Progression", text: "Start with short rolls just past the knees. Increase range as strength develops." }] },
      { name: "Side Plank", muscles: ["Obliques", "Glutes"], category: "Core Stage 2", order: 8, sets: 2, reps: "30–45 sec each side", rest: "45 sec", eccentric: "—", why: "Anti-lateral flexion — complements the Pallof press anti-rotation work on Friday. Together they cover all three planes of anti-movement core training.", form: [{ label: "Hips", text: "Drive the hips up. They should never sag. If they drop, the set is over." }, { label: "Squeeze", text: "Squeeze the glutes and brace the abs simultaneously." }, { label: "Watch for", text: "Hips sagging, top shoulder rotating toward the floor, holding the breath." }] },
      { name: "Plank", muscles: ["Core", "Glutes"], category: "Core Stage 1", order: 9, sets: 2, reps: "45–60 sec", rest: "45 sec", eccentric: "—", why: "Stage 1 baseline held throughout the program. Teaches the full-body brace needed in every compound lift.", form: [{ label: "Squeeze", text: "Squeeze the glutes, brace the abs, and push the floor away with the forearms all at once." }, { label: "Progression", text: "Once 60 seconds feels easy, add shoulder taps — tap each shoulder alternately while keeping the body rigid." }] },
    ],
  },
  {
    day: "SUN", label: "Rest", type: "rest",
    focus: "Active Recovery",
    muscles: [],
    exercises: [
      { name: "Light Walk", muscles: ["Full Body"], category: "Recovery", order: 1, sets: 1, reps: "20–30 min", rest: "—", eccentric: "—", why: "Easy movement supports blood flow and nutrient delivery.", form: [{ label: "Pace", text: "Fully conversational. Outdoors if possible." }] },
      { name: "Hip Flexor Stretch", muscles: ["Hip Flexors"], category: "Mobility", order: 2, sets: 2, reps: "60 sec each side", rest: "30 sec", eccentric: "—", why: "Heavy split squats and lunges shorten the hip flexors over time.", form: [{ label: "Position", text: "Kneeling lunge. Push the front hip gently forward. 60 seconds each side." }] },
      { name: "Chest and Shoulder Doorway Stretch", muscles: ["Chest", "Front Delt"], category: "Mobility", order: 3, sets: 2, reps: "30–45 sec each side", rest: "30 sec", eccentric: "—", why: "Four push sessions per week creates anterior tightness — this directly counters it.", form: [{ label: "Position", text: "Forearm on doorframe at 90°. Lean gently through the doorway." }] },
      { name: "Cat-Cow", muscles: ["Spine", "Core"], category: "Mobility", order: 4, sets: 2, reps: "10 slow reps", rest: "—", eccentric: "—", why: "Spinal mobility to reduce stiffness from the week's loading.", form: [{ label: "Movement", text: "On hands and knees. Breathe in as you arch (cow). Breathe out as you round (cat). Slow and deliberate." }] },
      { name: "Foam Roll", muscles: ["Full Body"], category: "Recovery", order: 5, sets: 1, reps: "5–10 min", rest: "—", eccentric: "—", why: "Reduces perceived soreness.", form: [{ label: "Technique", text: "Move slowly. Hold tender spots for 20–30 seconds. Priority: quads, hamstrings, glutes, upper back." }] },
    ],
  },
];

export const principles = [
  {
    section: "Training Principles",
    entries: [
      { title: "Progressive Overload", body: "The only mechanism that drives strength and muscle growth over time. Add one rep or 2.5 to 5 lbs per exercise per session — whichever comes first. When you hit the top of the rep range across all sets with clean form, increase the load next session. Log every session. Without data there is no overload, and without overload there is no adaptation. NASM refers to this as the principle of progressive overload within the OPT model." },
      { title: "Eccentric Phase", body: "The lowering portion of every rep — also called the negative — is where the majority of the hypertrophic stimulus occurs. Eccentric loading causes more muscle fiber recruitment and greater micro-damage, which drives the repair and growth response. Every exercise in this program prescribes a 2 to 3 second descent. Control the weight down. Do not drop it." },
      { title: "Rest Periods", body: "2 to 3 minutes between compound sets. 90 seconds to 2 minutes between isolation sets. Longer rest periods allow the phosphocreatine energy system to partially replenish, which means better performance on the next set, which means more total volume over the session. Volume is the primary driver of hypertrophy. Time your rest — guessing always undershoots it." },
      { title: "Compound vs. Isolation Exercises", body: "Compound movements recruit multiple muscle groups and joints simultaneously — presses, rows, squats, hinges. They go first in every session when the neuromuscular system is fresh and can handle the heaviest loads. Isolation exercises target a single muscle — curls, fly variations, lateral raises. They follow compounds to accumulate volume in specific areas. NASM classifies these as multi-joint and single-joint movements within the resistance training component of the OPT model." },
      { title: "Training Frequency", body: "Every muscle group in this program is trained twice per week. This is supported by research as the optimal frequency for hypertrophy for most individuals — enough stimulus per week to drive adaptation, with enough recovery between sessions to allow it. The Push Pull Legs structure achieves this naturally: each muscle pattern appears once in the first three days and repeats in the second three." },
    ]
  },
  {
    section: "Program Structure",
    entries: [
      { title: "Why Push Pull Legs", body: "Push Pull Legs splits training by movement pattern rather than arbitrary muscle groupings. Push sessions — chest, shoulders, triceps — involve muscles that push or extend. Pull sessions — back, biceps, rear delts — involve muscles that pull or flex. Legs — quads, glutes, hamstrings, calves — get their own dedicated sessions. Running this twice per week gives every muscle group two quality sessions at sufficient volume without overlap or overuse." },
      { title: "Exercise Order Within Sessions", body: "Heaviest compound movements go first — always. The central nervous system performs best at the start of a session before fatigue accumulates. Placing heavy bilateral compounds at the top of the session means more weight moved, better form, and greater strength development. Unilateral exercises follow bilateral. Isolation exercises come last. Core and abs finish every session — fatigued stabilizers during heavy compound movements increase injury risk." },
      { title: "Core Progression — Stages 1, 2, and 3", body: "Core training follows a three-stage progression aligned with NASM's stabilization-strength-power model. Stage 1 is deep stabilization — exercises like Dead Bug and Plank that train the transverse abdominis and diaphragm to resist spinal movement. Stage 2 is anti-movement — Pallof Press and Side Plank train the core to resist rotation and lateral flexion, which is what it actually does during every compound lift. Stage 3 is loaded and dynamic — Hanging Knee Raise and Ab Wheel Rollout add external load and full range of motion. Each stage must be solid before progressing." },
      { title: "Addressing Left-Right Imbalances", body: "Bilateral exercises — where both sides move together — can mask strength and size differences because the dominant side compensates for the weaker. Unilateral exercises remove that compensation. This program includes single-arm and single-leg variations throughout to identify and close those gaps. Always start with the weaker side. Match exactly with the stronger side. Never add load until both sides are equal for two consecutive sessions." },
      { title: "Cardio — Placement and Zone", body: "Cardio is placed after resistance training — never before. Performing cardio first depletes glycogen and accumulates fatigue that directly reduces performance on compound movements. Post-lift cardio takes advantage of elevated heart rate and metabolic demand already present. Zone 3 training — 65 to 75 percent of maximum heart rate — targets aerobic capacity and fat oxidation without the recovery cost of higher-intensity work. Breathing is noticeably elevated at Zone 3 but sustainable for 20 minutes." },
    ]
  },
  {
    section: "Recovery",
    entries: [
      { title: "Core Bracing", body: "Before every compound set: breathe into the belly so the abdomen expands, not the chest. Then brace the abs like you are about to take a hit — hard in all directions. Hold that brace for the entire rep. This creates intra-abdominal pressure, which stabilizes the spine, protects the intervertebral discs, and allows more force to transfer to the working muscle. Releasing the brace mid-rep on heavy loads is where injuries happen." },
      { title: "Sleep and Recovery", body: "Muscle repair and growth hormone release occur primarily during deep sleep. 7 to 9 hours per night is the evidence-based target for active individuals. Sleep deprivation reduces testosterone, increases cortisol, impairs neuromuscular performance, and slows fat loss — all working against what training is trying to accomplish. Recovery is not separate from training. It is half of it." },
      { title: "Active Recovery", body: "On rest days, light movement — walking, mobility work, foam rolling — promotes blood flow and nutrient delivery to recovering muscles without adding training stress. This is why Sunday includes a structured light session rather than complete rest. Complete inactivity on rest days can actually slow recovery relative to light movement." },
      { title: "Delayed Onset Muscle Soreness (DOMS)", body: "DOMS is the soreness felt 24 to 72 hours after training — caused by the micro-damage of eccentric loading that triggers the repair and growth response. It is normal, expected, and does not indicate injury. DOMS is most pronounced when a new exercise, rep range, or load is introduced. It diminishes as the body adapts. Training through mild DOMS is appropriate. Sharp or joint-level pain is not DOMS — it is a signal to stop and assess." },
    ]
  },
  {
    section: "Nutrition Basics",
    entries: [
      { title: "Protein and Muscle Protein Synthesis", body: "Muscle protein synthesis — the process of building new muscle tissue — requires dietary protein as the substrate. 1.6 to 2.2 grams of protein per kilogram of bodyweight per day is the evidence-based range for maximizing muscle growth in resistance-trained individuals. Spreading intake across 4 or more meals throughout the day optimizes synthesis rates better than consuming the same total in one or two large meals." },
      { title: "Caloric Targets and Body Composition", body: "Body recomposition — gaining muscle while losing fat simultaneously — requires a relatively small caloric deficit, adequate protein, and consistent resistance training. Aggressive caloric deficits accelerate fat loss but also accelerate muscle loss. Moderate deficits of 300 to 500 calories below maintenance, combined with high protein and progressive training, support muscle retention while losing fat. Training days and rest days can be cycled at different caloric levels to manage this." },
      { title: "Hydration", body: "Even mild dehydration — 2 percent of bodyweight — measurably reduces strength, power output, and cognitive performance. For a 170-pound individual, that is roughly 3.4 pounds or about 1.5 liters of water loss before performance is noticeably impaired. Training, sweating, and Zone 3 cardio all accelerate fluid loss. Water before, during, and after sessions is not optional." },
    ]
  },
  {
    section: "Glossary",
    entries: [
      { title: "1RM (One-Rep Max)", body: "The maximum weight you can lift for exactly one full repetition with proper form. Used as a baseline to set training loads. In this app, working weights are calculated as percentages of your estimated 1RM to give you target ranges for each goal — strength, muscle growth, or endurance." },
      { title: "Hypertrophy", body: "Skeletal muscle growth — the increase in size of individual muscle fibers in response to progressive resistance training and adequate nutrition. Hypertrophy is maximized in the 6 to 12 rep range at 67 to 85 percent of 1RM, with sufficient volume (sets) and appropriate rest." },
      { title: "Periodization", body: "The systematic variation of training variables — volume, intensity, frequency, exercise selection — over time to prevent plateaus, manage fatigue, and drive continued adaptation. NASM's OPT model is a periodization framework: it progresses from stabilization to strength to power phases across a training cycle." },
      { title: "RPE (Rate of Perceived Exertion)", body: "A subjective scale from 1 to 10 used to measure how hard a set feels. RPE 7 means 3 reps left in the tank. RPE 8 means 2 reps left. RPE 9 means 1 rep left. RPE 10 is absolute failure. Most working sets in this program target RPE 7 to 9 — challenging but not to failure." },
      { title: "FITT Principle", body: "A framework from NASM for designing training programs: Frequency (how often), Intensity (how hard), Time (how long), and Type (what kind of training). Every program decision — how many days per week, what heart rate zone for cardio, session duration, and training split — can be traced back to these four variables." },
      { title: "Supination and Pronation", body: "Supination is the rotation of the forearm so the palm faces upward. Pronation is the rotation so the palm faces downward. Relevant in curling movements: supinating during a curl maximizes bicep peak contraction. Neutral grip — thumb pointing up — targets the brachialis, the muscle underneath the bicep." },
      { title: "Bilateral vs. Unilateral", body: "Bilateral exercises involve both limbs simultaneously — barbell squat, dumbbell bench press, leg press. Unilateral exercises involve one limb at a time — single-arm row, Bulgarian split squat, single-leg curl. Bilateral exercises allow heavier loading. Unilateral exercises reveal and correct left-right strength asymmetries that bilateral exercises can mask." },
      { title: "Zone 3 Cardio", body: "Zone 3 is 65 to 75 percent of maximum heart rate. At this intensity, breathing is elevated — full comfortable conversation is not possible, but short sentences are. Zone 3 targets aerobic capacity and fat oxidation. It is harder than easy walking but easier than high-intensity intervals. 20 minutes post-lift at Zone 3 is the cardio target in this program." },
    ]
  },
];
